### ISSUE TITLE
variants condition 'finisherIdentifier in ["LogFormData"] not working

### ISSUE THREAD

**Issue by bh-teufels** [pagemachine/typo3-formlog#151]
i have field that i want to display only in finisher
the condition `condition: 'finisherIdentifier in ["EmailToSender", "EmailToReceiver", "Confirmation", "LogFormData"]'` 
working for Mails but not for LogFormData. The field does not appear in form log

my form.yaml looking like
```
-
            defaultValue: ''
            identifier: my-field-1
            label: my-field
            type: Text
            properties:
              fluidAdditionalAttributes:
                placeholder: 'my-field (hidden)'
              elementDescription: 'filled in automatically'
            variants:
              -
                identifier: hide-in-form
                condition: 'stepIdentifier == "page-1"'
                renderingOptions:
                  enabled: false
              -
                identifier: show-in-email
                condition: 'finisherIdentifier in ["EmailToSender", "EmailToReceiver", "Confirmation", "LogFormData"]'
                renderingOptions:
                  enabled: true
```
